name: ShadowRadius
author: minhlong139
category: Interface
tags: [border, corner, radius, shadow]
docs: http://minhlong139.plus.vn/ShadowRadius/Docs/
demo: http://minhlong139.plus.vn/ShadowRadius/demo/
current: 1.0
